parameters:
#    arnaud_cv.example.class: Arnaud\CvBundle\Example

services:
#    arnaud_cv.example:
#        class: %arnaud_cv.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
