<?php

namespace Arnaud\CvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{

    public function getJobsWithTasks()
    {
        $qb = $this->createQueryBuilder('j')
                   ->leftJoin('j.tasks', 't')
                   ->addSelect('t');

        return $qb->getQuery()
                  ->getResult();
    }

    public function findAllOrdered()
    {
        $qb = $this->createQueryBuilder('j')
                   ->orderBy('j.start','DESC');

        return $qb->getQuery()
                  ->getResult();
    }
}
