arnaud_main_index:
    pattern: /
    defaults: { _controller: ArnaudMainBundle:Default:index }

arnaud_cv_index:
    pattern: /cv
    defaults: { _controller: ArnaudCvBundle:Default:index }

arnaud_cv_add_job:
    pattern: /cv/add/job
    defaults: { _controller: ArnaudCvBundle:Default:addJob }

arnaud_cv_update_job:
    pattern: /cv/update/job/{id}
    defaults: { _controller: ArnaudCvBundle:Default:updateJob }

arnaud_cv_delete_job:
    pattern: /cv/delete/job/{id}
    defaults: { _controller: ArnaudCvBundle:Default:deleteJob }

arnaud_user_add_default:
    pattern: /user/add_default
    defaults: { _controller: ArnaudUserBundle:Default:addDefault }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#arnaud_main:
#    pattern:  /
#    defaults: { _controller: ArnaudMainBundle:Default:index }

#arnaud_main:
#    resource: "@ArnaudMainBundle/Resources/config/routing.yml"

#arnaud_cv:
#    resource: "@ArnaudCvBundle/Resources/config/routing.yml"

#arnaud_cv:
#    pattern: /cv
#    defaults: { _controller: ArnaudCvBundle:Default:index }


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
