parameters:
#    arnaud_main.example.class: Arnaud\MainBundle\Example

services:
#    arnaud_main.example:
#        class: %arnaud_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
